import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { styled } from "@stitches/react";
import styles from "../styles/index";
import flex from "../styles/layout/flex";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jeff Brausam Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <StyledHeader>
        <div
          style={{
            borderRadius: "50%",
            margin: "2rem 2rem 2rem 0",
          }}
        >
          <StyledProfilePic
            src="/images/profilepic.jpg"
            alt="me"
            width="100"
            height="100"
          />
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <strong style={{ fontSize: "1.4rem", margin: 0 }}>
            Jeff Brausam
          </strong>
          <p
            style={{
              color: styles.color.gray500,
              margin: `${styles.spacing.size1} 0`,
            }}
          >
            Software Engineer
          </p>
          <div
            style={{
              margin: `${styles.spacing.size1} 0`,
              color: styles.color.gray600,
            }}
          >
            <Link href="https://github.com/Jeff-Brausam" passHref>
              <StyledLink>Github</StyledLink>
            </Link>{" "}
            |{" "}
            <Link
              href="https://www.linkedin.com/in/jeff-brausam-7584a2125/"
              passHref
            >
              <StyledLink>Linkedin</StyledLink>
            </Link>{" "}
            |{" "}
            <Link href="mailto:jeffbrausam@gmail.com" passHref>
              <StyledLink>Email</StyledLink>
            </Link>
          </div>
        </div>
      </StyledHeader>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Container>
          <div>
            <h3
              style={{
                fontSize: styles.typography.fontsize.text2xl.size,
                fontWeight: "500",
                marginTop: styles.spacing.size12,
                marginBottom: styles.spacing.size4,
              }}
            >
              Featured Work
            </h3>
            <hr style={{ color: styles.color.lime400, width: "100%" }} />
          </div>
          <ProjectContainer>
            <VideoWrapper>
              <StyledVideo playsInline={true} loop={true} autoPlay={true}>
                <source src="lunde_water.mp4" type="video/mp4" />
                <source src="lunde_water.mp4" type="video/mov" />
              </StyledVideo>
            </VideoWrapper>
            <div>
              <h3
                style={{
                  marginBottom: "0",
                  color: styles.color.gray500,
                  fontWeight: 500,
                }}
              >
                Lunde Water
              </h3>
              <p
                style={{
                  color: styles.color.gray400,
                  marginTop: styles.spacing.size2,
                  fontSize: styles.typography.fontsize.textsm.size,
                }}
              >
                Water Delivery application using an MERN stack with Typescript.
                Created and implemented a custom algorithm to interact with T
                Sheets API, that scans employee timesheets and creates a
                calendar of available booking dates based on that data. Used
                RESTful design principles for API communication. Created role
                based user authentication for different authorization levels.{" "}
              </p>
            </div>
            <div
              style={{
                width: styles.sizing.width.size44,
                display: "flex",
                justifyContent: "space-evenly",
                alignSelf: "flex-end",
              }}
            >
              {/* TODO: Add live link */}
              {/* <Link href="https://jeff-brausam.github.io/mockup-online-store">
                <a>
                  <StyledProjectButton>Demo</StyledProjectButton>
                </a>
              </Link> */}
            </div>
          </ProjectContainer>
          {/* Mockup */}
          <ProjectContainer>
            <VideoWrapper>
              <StyledVideo playsInline={true} loop={true} autoPlay={true}>
                <source src="mockup.mp4" type="video/mp4" />
                <source src="mockup.mp4" type="video/mov" />
              </StyledVideo>
            </VideoWrapper>
            <div>
              <h3
                style={{
                  marginBottom: "0",
                  color: styles.color.gray500,
                  fontWeight: 500,
                }}
              >
                Mockup
              </h3>
              <p
                style={{
                  color: styles.color.gray400,
                  marginTop: styles.spacing.size2,
                  fontSize: styles.typography.fontsize.textsm.size,
                }}
              >
                Mockup is an ecommerce store built with React for the frontend
                and Firebase for backend serverside needs. Used react router for
                routing between pages, and Redux for state management.{" "}
              </p>
            </div>
            <div
              style={{
                width: styles.sizing.width.size44,
                display: "flex",
                justifyContent: "space-evenly",
                alignSelf: "flex-end",
              }}
            >
              <Link href="https://jeff-brausam.github.io/mockup-online-store">
                <a>
                  <StyledProjectButton>Demo</StyledProjectButton>
                </a>
              </Link>
              <Link href="https://github.com/Jeff-Brausam/mockup-online-store">
                <a>
                  <StyledProjectButton>Repo</StyledProjectButton>
                </a>
              </Link>
            </div>
          </ProjectContainer>
          {/* Calculator */}
          <ProjectContainer>
            <VideoWrapper>
              <StyledVideo playsInline={true} loop={true} autoPlay={true}>
                <source src="calculator.mp4" type="video/mp4" />
                <source src="calculator.mp4" type="video/mov" />
              </StyledVideo>
            </VideoWrapper>
            <div>
              <h3
                style={{
                  marginBottom: "0",
                  color: styles.color.gray500,
                  fontWeight: 500,
                }}
              >
                Calculator
              </h3>
              <p
                style={{
                  color: styles.color.gray400,
                  marginTop: styles.spacing.size2,
                  fontSize: styles.typography.fontsize.textsm.size,
                }}
              >
                An application built with Javascript using ES5 syntax, with the
                purpose of solving math equations with precision and ease.{" "}
              </p>
            </div>
            <div
              style={{
                width: styles.sizing.width.size44,
                display: "flex",
                justifyContent: "space-evenly",
                alignSelf: "flex-end",
              }}
            >
              <Link href="https://jeff-brausam.github.io/calculator-app">
                <a>
                  <StyledProjectButton>Demo</StyledProjectButton>
                </a>
              </Link>
              <Link href="https://github.com/Jeff-Brausam/calculator-app">
                <a>
                  <StyledProjectButton>Repo</StyledProjectButton>
                </a>
              </Link>
            </div>
          </ProjectContainer>
          {/* To-do List */}
          <ProjectContainer>
            <VideoWrapper>
              <StyledVideo playsInline={true} loop={true} autoPlay={true}>
                <source src="todolist.mp4" type="video/mp4" />
                <source src="calculator.mp4" type="video/mov" />
              </StyledVideo>
            </VideoWrapper>
            <div>
              <h3
                style={{
                  marginBottom: "0",
                  color: styles.color.gray500,
                  fontWeight: 500,
                }}
              >
                To-do List
              </h3>
              <p
                style={{
                  color: styles.color.gray400,
                  marginTop: styles.spacing.size2,
                  fontSize: styles.typography.fontsize.textsm.size,
                }}
              >
                Built in React, a user may create, edit, and delete a to-do
                item. Persisted storage for users through localStorage.{" "}
              </p>
            </div>
            <div
              style={{
                width: styles.sizing.width.size44,
                display: "flex",
                justifyContent: "space-evenly",
                alignSelf: "flex-end",
              }}
            >
              <Link href="https://jeff-brausam.github.io/to-do-list">
                <a>
                  <StyledProjectButton>Demo</StyledProjectButton>
                </a>
              </Link>
              <Link href="https://github.com/Jeff-Brausam/to-do-list">
                <a>
                  <StyledProjectButton>Repo</StyledProjectButton>
                </a>
              </Link>
            </div>
          </ProjectContainer>
          <ProjectContainer>
            <StyledProjectImage
              src="/images/WeatherAppScreenshot.jpg"
              width={1400}
              height={720}
            />
            <div>
              <h3
                style={{
                  marginBottom: "0",
                  color: styles.color.gray500,
                  fontWeight: 500,
                }}
              >
                Weather Application
              </h3>
              <p
                style={{
                  color: styles.color.gray400,
                  marginTop: styles.spacing.size2,
                  fontSize: styles.typography.fontsize.textsm.size,
                }}
              >
                Built using Javascript, HTML5, CSS, a very minimal application
                that allows a user to search and find the 5-day forecast in
                their city.{" "}
              </p>
            </div>
            <div
              style={{
                width: styles.sizing.width.size44,
                display: "flex",
                justifyContent: "space-evenly",
                alignSelf: "flex-end",
              }}
            >
              <Link href="https://jeff-brausam.github.io/weather-app">
                <a>
                  <StyledProjectButton>Demo</StyledProjectButton>
                </a>
              </Link>
              <Link href="https://github.com/Jeff-Brausam/weather-app">
                <a>
                  <StyledProjectButton>Repo</StyledProjectButton>
                </a>
              </Link>
            </div>
          </ProjectContainer>
        </Container>
      </div>
    </div>
  );
}

const StyledLink = styled("a", {
  "&:hover": {
    color: styles.color.emerald600,
    cursor: "pointer",
  },
});

const StyledHeader = styled("header", {
  background: styles.color.gray100,
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
});

const StyledProfilePic = styled(Image, {
  borderRadius: "50%",
  boxShadow: styles.effect.boxshadow.shadowmd,
});

const Container = styled("div", {
  maxWidth: styles.layout.container.medium,

  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  flexDirection: "column",
});

const ProjectContainer = styled("div", {
  padding: "1rem",
  display: "flex",
  margin: styles.spacing.size10,
  alignItems: "center",
  justifyContent: "center",
  flexDirection: "column",
  boxShadow: styles.effect.boxshadow.shadowmd,
});

const VideoWrapper = styled("div", {
  maxWidth: "100%",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
});

const StyledVideo = styled("video", {
  maxWidth: "100%",
  flex: styles.layout.flex.basis.flex1,
});

const StyledProjectImage = styled(Image, {
  border: "1px solid red",
  margin: styles.spacing.size8,
  boxShadow: styles.effect.boxshadow.shadowmd,
});

const StyledProjectButton = styled("button", {
  width: styles.sizing.width.size14,
  height: styles.sizing.height.size6,
  borderRadius: "25px",
  border: `1px solid ${styles.color.gray500}`,
  background: "white",
  color: styles.color.gray500,
  "&:hover": {
    color: styles.color.lime600,
    border: `1px solid ${styles.color.lime600}`,
    cursor: "pointer",
  },
});
